# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fe9971d4c87626bcf8280cf64f35666"
name = "serail-validator"
application_url = "https://serial-validator-shopify-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Comment these out for development - require protected customer data approval
  # [[webhooks.subscriptions]]
  # topics = [ "orders/paid" ]
  # uri = "/webhooks/orders/paid"

  # [[webhooks.subscriptions]]
  # topics = [ "orders/cancelled" ]
  # uri = "/webhooks/orders/cancelled"

  # [[webhooks.subscriptions]]
  # topics = [ "refunds/create" ]
  # uri = "/webhooks/refunds/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [ "https://serial-validator-shopify-app-production.up.railway.app/api/auth" ]
